language: go
go:
- 1.7.x
- 1.8.x
- 1.9.x
env:
- GIMME_OS=linux GIMME_ARCH=arm
script:
- go build -o pi-init2 github.com/mdehaas/pi-init2/src/pi-init2
before_deploy:
- zip -r pi-init2.zip cmdline.txt boot pi-init2
deploy:
  provider: releases
  skip_cleanup: true
  file: pi-init2.zip
  on:
    repo: mdehaas/pi-init2
    tags: true
